# Generated by Django 5.0 on 2024-07-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav_app', '0002_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.JSONField(),
        ),
    ]
