# Generated by Django 5.0 on 2024-07-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav_app', '0003_alter_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='location_images/'),
        ),
        migrations.AddField(
            model_name='location',
            name='open_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='reviews',
            field=models.TextField(blank=True, null=True),
        ),
    ]
